export const DRIFT_LABELS: Record<string, string> = {
  snaccs_count: "Snaccs per user",
  followers_count: "Followers",
  following_count: "Following",
  total_views_received: "Views received",
  unread_notifications_count: "Unread notifications",
  score: "Snacc Score vs ledger",
  tier: "Tier vs ladder",
  reactions_received: "Reactions received",
  resnaccs_received: "Resnaccs received",
  comments_received: "Comments received",
  reactions_count: "Reactions per snacc",
  resnaccs_count: "Resnaccs per snacc",
  views_count: "Views per snacc",
  comments_count: "Comments per snacc",
  quotes_count: "Quotes per snacc",
  bookmarks_count: "Bookmarks per snacc",
  hides_count: "Hides per snacc",
  reports_count: "Reports per snacc",
  opens_count: "Opens per snacc",
  dwell_ms_total: "Dwell time per snacc",
  shares_count: "Shares per snacc",
  author_taps_count: "Author taps per snacc",
  wallet_balances: "Wallet balances vs ledger",
  earnings_balances: "Earnings balances vs ledger",
}
