// Generated by the backend (`npm run keys:app`) from config.defaults.ts and
// feature-flags.defaults.ts. Do not edit by hand.

export const FLAG_KEYS = [
  "giphy",
  "snacc_gifs",
  "snacc_matches",
  "message_gifs",
  "search",
  "earnings",
  "reactions",
  "resnacc",
  "post_pinning",
  "post_editing",
  "anon_messages",
  "first_post_prompt",
  "profile_visitors",
  "profile_photo_upload",
  "avatar_customization",
  "bookmarks",
  "hides",
  "feed_global",
  "feed_following",
  "feed_ranking",
  "message_images",
  "message_view_once",
  "message_editing",
  "voice_notes",
  "voice_snaccs",
  "chat_streaks",
  "score",
  "og_badge",
  "notifications_push",
  "notifications_digest",
  "ghost_hour",
  "moments",
  "stickers",
  "snacc_stickers",
  "message_stickers",
  "premium_wallet",
  "premium",
  "wallet",
  "wallet_dva",
  "admin_report_alerts",
  "moderation",
  "moderation_enforce",
  "app_icon",
  "polls",
  "easter_eggs",
  "live_scores",
  "accent_colors",
  "realtime",
] as const

export const PUBLIC_CONFIG_DEFAULTS: {
  readonly "eggs.burst_counts": object
  readonly "content.snacc.body_max_length": number
  readonly "content.snacc.max_images": number
  readonly "content.snacc.voice_max_seconds": number
  readonly "content.snacc.edit_window_minutes": number
  readonly "content.message.edit_window_minutes": number
  readonly "content.message.body_max_length": number
  readonly "content.message.max_images": number
  readonly "content.message.voice_max_seconds": number
  readonly "content.sticker.max_edge": number
  readonly "content.sticker.library_max": number
  readonly "messages.streak_grace_days": number
  readonly "messages.streak_min_days": number
  readonly "messages.streak_milestones": readonly string[]
  readonly "moderation.suspension.durations_days": readonly string[]
  readonly "content.report.detail_max_length": number
  readonly "profile.username.max_length": number
  readonly "content.poll.max_options": number
  readonly "content.poll.option_max_length": number
  readonly "content.poll.min_minutes": number
  readonly "content.poll.max_minutes": number
  readonly "profile.display_name.max_length": number
  readonly "profile.bio.max_length": number
  readonly "discovery.popular_hashtags.limit": number
  readonly "views.record.max_batch": number
  readonly "earn.withdrawal.balance": number
  readonly "wallet.send.min_kobo": number
  readonly "wallet.send.bank_fee_kobo": number
  readonly "wallet.confirm.user_stepup_threshold_kobo": number
  readonly "wallet.confirm.bank_stepup_threshold_kobo": number
  readonly "wallet.request.expiry_days": number
  readonly "wallet.deposit.min_kobo": number
  readonly "wallet.deposit.max_kobo": number
  readonly "wallet.limits.basic.daily_send_kobo": number
  readonly "wallet.limits.basic.daily_bank_send_kobo": number
  readonly "wallet.limits.basic.daily_deposit_kobo": number
  readonly "wallet.limits.verified.daily_send_kobo": number
  readonly "wallet.limits.verified.daily_bank_send_kobo": number
  readonly "wallet.limits.verified.daily_deposit_kobo": number
  readonly "wallet.dva.requires_identity": boolean
  readonly "earn.withdrawal.views": number
  readonly "earn.withdrawal.followers": number
  readonly "earn.withdrawal.account_age_days": number
  readonly "client.min_version": string
  readonly "premium.wallet.monthly_kobo": number
  readonly "premium.wallet.yearly_kobo": number
  readonly "client.min_version_ios": string
  readonly "client.min_version_android": string
  readonly "client.store_url_android": string
  readonly "client.store_url_ios": string
  readonly "ghost.window.minutes": number
  readonly "avatar.base": string
  readonly "avatar.style": string
  readonly "avatar.format": string
  readonly "moments.ttl_hours": number
  readonly "moments.max_per_day": number
  readonly "moments.caption_max_length": number
  readonly "moments.reactions": readonly string[]
  readonly "score.floor.unique_engagers": number
  readonly "score.daily.full_posts": number
  readonly "score.daily.half_posts": number
  readonly "score.actor.daily_cap": number
  readonly "premium.rc_ios_key": string
  readonly "premium.rc_android_key": string
  readonly "premium.offering_id": string
  readonly "premium.trial_days": number
} = {
  "eggs.burst_counts": {
    common: 10,
    uncommon: 14,
    rare: 20,
    epic: 28,
    legendary: 36,
  },
  "content.snacc.body_max_length": 500,
  "content.snacc.max_images": 10,
  "content.snacc.voice_max_seconds": 300,
  "content.snacc.edit_window_minutes": 15,
  "content.message.edit_window_minutes": 5,
  "content.message.body_max_length": 500,
  "content.message.max_images": 4,
  "content.message.voice_max_seconds": 120,
  "content.sticker.max_edge": 512,
  "content.sticker.library_max": 200,
  "messages.streak_grace_days": 1,
  "messages.streak_min_days": 2,
  "messages.streak_milestones": ["3", "7", "14", "30", "50", "100"],
  "moderation.suspension.durations_days": ["1", "3", "7", "30"],
  "content.report.detail_max_length": 500,
  "profile.username.max_length": 30,
  "content.poll.max_options": 4,
  "content.poll.option_max_length": 50,
  "content.poll.min_minutes": 5,
  "content.poll.max_minutes": 10080,
  "profile.display_name.max_length": 50,
  "profile.bio.max_length": 160,
  "discovery.popular_hashtags.limit": 15,
  "views.record.max_batch": 50,
  "earn.withdrawal.balance": 100000,
  "wallet.send.min_kobo": 10000,
  "wallet.send.bank_fee_kobo": 2500,
  "wallet.confirm.user_stepup_threshold_kobo": 500000,
  "wallet.confirm.bank_stepup_threshold_kobo": 2000000,
  "wallet.request.expiry_days": 7,
  "wallet.deposit.min_kobo": 10000,
  "wallet.deposit.max_kobo": 5000000,
  "wallet.limits.basic.daily_send_kobo": 5000000,
  "wallet.limits.basic.daily_bank_send_kobo": 2000000,
  "wallet.limits.basic.daily_deposit_kobo": 10000000,
  "wallet.limits.verified.daily_send_kobo": 50000000,
  "wallet.limits.verified.daily_bank_send_kobo": 20000000,
  "wallet.limits.verified.daily_deposit_kobo": 100000000,
  "wallet.dva.requires_identity": true,
  "earn.withdrawal.views": 5000,
  "earn.withdrawal.followers": 50,
  "earn.withdrawal.account_age_days": 14,
  "client.min_version": "0.0.0",
  "premium.wallet.monthly_kobo": 350000,
  "premium.wallet.yearly_kobo": 3200000,
  "client.min_version_ios": "",
  "client.min_version_android": "",
  "client.store_url_android":
    "https://play.google.com/store/apps/details?id=com.snacc.fyi",
  "client.store_url_ios": "",
  "ghost.window.minutes": 10,
  "avatar.base": "https://api.dicebear.com/9.x",
  "avatar.style": "adventurer",
  "avatar.format": "png",
  "moments.ttl_hours": 24,
  "moments.max_per_day": 20,
  "moments.caption_max_length": 200,
  "moments.reactions": ["❤️", "😂", "🔥", "😮", "😢", "👏"],
  "score.floor.unique_engagers": 3,
  "score.daily.full_posts": 20,
  "score.daily.half_posts": 20,
  "score.actor.daily_cap": 25,
  "premium.rc_ios_key": "",
  "premium.rc_android_key": "",
  "premium.offering_id": "",
  "premium.trial_days": 0,
}
